export const ICE_BREAKERS: string[] = [
  'What incredibly common thing have you never done?',
  'What was your most memorable dream?',
  'What household chore do you actually enjoy?',
  'What is your favourite emoji?',
  'Who is the funniest person on your team?',
  "What's the best thing you've got going on in your life at the moment?",
  'What has taken you the longest to get good or decent at?',
  "What was the funniest thing you've seen recently online?",
  'What are some of your favorite games to play?',
  'What scene in a movie always gives you goosebumps every time you watch it?',
  'What topic could you give a 20-minute presentation on without any preparation?',
  "What's something that a lot of people are missing out on because they don't know about it?",
  "Who is the most interesting person you've met and talked with?",
  'How did you spend the money from your very first job?',
  'What do you wish someone taught you a long time ago?',
  "What's your favorite car that you've owned or driven?",
  "What subjects should be taught in school but aren't?",
  'Do you think you have a pretty good work-life balance? Why or why not?',
  'What was the last thing you were really excited about?',
  'What does your perfect breakfast look like?',
  'If you could choose your dreams, what would you prefer to dream about?',
  "What's something that was once important but is now becoming less and less relevant?",
  'What is the best pair of shoes you have owned?',
  'What do you buy way more of than most people?',
  'What wastes the most time in your day to day life?',
  "What's the most annoying machine you must deal with regularly?",
  'What are you grateful for?',
  'What hobby would be a lot of fun to get into?',
  'What do you resent paying for most?',
  'What pets did you have growing up?',
  "What's the best or worst prank you've played on someone?",
  "What was the scariest movie you've seen?",
  'What motivates you?',
  'What skill or talent would you most like to learn?',
  'What culture would you like to learn more about?',
  'What do you wish your phone could do?',
  "What's your favorite international food?",
  'What kind of physical activities do you like doing?',
  'What big problem do you think technology will solve next?',
  'How do you think you will be/act when you are old?',
  "What's your favorite way to waste time online?",
  'What was something you thought would be easy until you tried it?',
  'What is your favourite animal?',
  "What is the biggest mistake you've made at work?",
  'What were your favorite television shows when you were growing up?',
  "What's a hidden skill that you have?",
  'What do you want to do when you retire?',
  'What do you do to unwind after a hard day?',
  'Would you rather spend time with other people or at home alone?',
  'What music do you put on when you want to get pumped?',
  'What makes you feel old when you think about it?',
  'What was your funniest or worst experience with a dentist?',
  'What are your favorite snacks?',
  'What TV show are you hooked on or were recently hooked on?',
  'If you had to lose one of your senses, which would you choose to lose?',
  "What did your teachers and parents say would be really important when you grew up, but it hasn't been?",
  'What is your favorite genre of movie? Why?',
  'What brands do you love/hate the most?',
  'What would you change if you were in charge of the company you work for?',
  "What's the most outdated piece of tech you still use regularly?",
  "What's the weirdest food you've eaten?",
  'Who was your favorite teacher?',
  'How often do you dance?',
  "What's your favorite thing about where you live?",
  "What's the best day you've had recently?",
  "What's your favorite way to spend time outdoors?",
  "What's the best advice you've been given?",
  "What's the worst advice you've been given?",
  'If the universe is just a simulation, what update or patch does it need?',
  'Where have you traveled to?',
  "What's the most unique shop or restaurant you've been in?",
  'What hard time in your life left you a better person after it was finished?',
  "What's the best sports game you've been to?",
  "What's something you're looking forward to?",
  'What was a time you were totally out of your element/comfort zone?',
  'What kind of people do you most enjoy hanging out with?',
  'What do you think the ideal age to be is?',
  'What is the best thing you have ever bought?',
  'What luxury is totally worth the price?',
  'What is the most unique or silliest problem you have going on in your life at the moment?',
  'What apps do you use most?',
  'Why is Kiele the GOAT?',
  'What do you geek out about?',
  "What's your favorite month?",
  "What's the best concert you've been to and why was it so good?",
  "What's your biggest irrational phobia and why?",
  'If you could have any superpower what would it be?',
  'If you could be somebody else for a day who would you be?',
  'If you could time travel, where is the first place you would go?',
  'If you could be reincarnated as any animal, which one would you choose?',
  'Who on the team would you want by your side during a zombie apocalypse?',
  'If you could teleport anywhere in the world right now, where would you go?',
  'Would you rather have more money or more time?',
  "Would you rather lose the ability to lie or believe everything you're told?",
  "Would you rather speak to animals or know other people's thoughts?",
  'If you could learn any language from another country which would you choose?',
  "What's the most important thing you have on or near your desk right now?",
  'What is your go-to drink or snack while working?',
  'Which website do you most often defer to when procrastinating?',
  'How often do you work from your bed?',
  'Who on the team is most likely to write a book?',
  'What was the moment you realised you were officially an adult?',
  'Would you rather have wings or breathe underwater?',
  'What do you think was the most important invention in history?',
  'Name one colleague who is the most likely to escape a deserted island alive?',
  'If given the opportunity to be the boss for a day, which is the first thing you would do?',
  'What is your favorite thing about your team?',
  "What's the best thing about working from home?",
  "What's the worst thing about working from home?",
  'If trapped in a horror movie, who would be the first one to die from your team?',
  'If given the option to time travel to your past and give yourself some advice, which age would you choose to go to?',
  "What is the coolest website you've ever visited?",
  'You can not time travel, but your phone has the internet from 5 years in the future. What do you search for first?',
  "What's on your bucket list?",
  "What's something you've tried that you will never do again?",
  'What is your favorite genre of music?',
  'In high school, what was the stupidest thing you did?',
  'What type of person do you love working with the most?',
  'If you could pick one coworker to switch lives with, who would it be?',
  'What was the funniest thing that happened to you at work?',
  'Which colleague has the best fashion sense?',
  "What's your favorite meme or viral video?",
  'If you never had to sleep, what would you do with all those extra hours each day?',
  "What's the story behind your name?",
  'What job would you be terrible at?',
  'Would you rather live forever but have a boring life, or live a short but amazing life?',
  'If you could eliminate one thing from your daily routine, what would it be and why?',
  'What was the last thing you bought?',
  'What was the last song you listened to?',
  'What was your best class in school?',
  "What is one bad habit you're trying to stop or have already stopped recently?",
  'What is your favorite letter of the alphabet?',
  'What characteristic do you value the most in your coworkers?',
  'Who in your team/company would you like to swap jobs with for a day?',
  'Cake or pie?',
  'If there was movie about your life, which actor would play you?',
  'If you were a character in SpongeBob SquarePants, which one would you be?',
  'If you were a character in Shrek, which one would you be?',
  'What is your favourite theme park ride?',
  'What condiments go on your hotdog?',
  'What toppings go on your pizza?',
  'What is your favourite ice cream flavour?',
  'What is your favourite cereal?',
  'What are your favourite chips?',
  'What is your favourite room in your house?',
  'Would you rather live your life as a dog or a cat?',
  'What is your favourite holiday?',
  'When you were a child, what did you want to be when you grew up?',
  'If you could only wear one colour for the rest of your life, what colour would you wear?',
  'Which seat do you prefer on a flight: window, middle, or aisle?',
  'What is your favorite self-care activity?',
  'What is your favourite trend to come out of the past 10 years?',
  'What outdated slang do you still use?',
];
