export const ICE_BREAKERS: string[] = [
  'What incredibly common thing have you never done?',
  'What was your most memorable dream?',
  'What household chore do you actually enjoy?',
  "What's the best thing you've got going on in your life at the moment?",
  "What was the funniest thing you've seen recently online?",
  'What are some of your favourite games to play?',
  'What topic could you give a 20-minute presentation on without any preparation?',
  "What's your favourite car that you've owned or driven?",
  "What subjects should be taught in school but aren't?",
  'Do you think you have a pretty good work-life balance? Why or why not?',
  'What was the last thing you were really excited about?',
  'If you could choose your dreams, what would you prefer to dream about?',
  'What do you buy way more of than most people?',
  'What motivates you?',
  'What skill or talent would you most like to learn?',
  'What were your favourite television shows when you were growing up?',
  'What TV show are you hooked on or were recently hooked on?',
  'What brands do you love/hate the most?',
  'How often do you dance?',
  "What's the best day you've had recently?",
  "What's the best advice you've been given?",
  "What's the worst advice you've been given?",
  "What's the best sports game you've been to?",
  "What's something you're looking forward to?",
  'What was a time you were totally out of your element/comfort zone?',
  'What kind of people do you most enjoy hanging out with?',
  'What is the best thing you have ever bought?',
  "What's the best concert you've been to and why was it so good?",
  'If you could be somebody else for a day who would you be?',
  'If you could learn any language from another country which would you choose?',
  "What's the most important thing you have on or near your desk right now?",
  'If given the opportunity to be the boss for a day, which is the first thing you would do?',
  "What's the worst thing about working from home?",
  'If trapped in a horror movie, who would be the first one to die from your team?',
  "What's on your bucket list?",
  'Would you rather live forever but have a boring life, or live a short but amazing life?',
  'What was the last thing you bought?',
  'What was the last song you listened to?',
  'If there was a movie about your life, which actor would play you?',
  'Have you been pleasantly surprised by anything lately?',
  'Pick the person whose turn is next. What is something that they say/do often?',
  'You have your own late-night talk show. Who do you invite as your first guest (dead or alive)?',
  'Would you rather talk like Yoda or breathe like Darth Vader?',
  'What is your go-to outfit when you want to feel confident and stylish?',
  'If you were a flavour of ice cream, what would you be, and why?',
  'If you could have any fictional technology or gadget from a movie, what would it be, and how would you use it?',
  'If you were a professional wrestler, what would be your signature move?',
  'What is your favourite gadget or piece of technology that you cannot live without?',
  'If you were stranded on a deserted island and could only bring three items, what would they be?',
  'If you could redesign the human body, what would you change or improve?',
  'Are you a morning person or a night owl?',
  'Adventure or relaxation?',
  "What is the most interesting fact you've learned recently?",
  'If you could witness any historical event, what would it be and why?',
  'If aliens visited Earth and you had to impress them with one skill, what would you do?',
  "What's your best 'dad joke' or pun?",
  'What is the most valuable lesson life has taught you so far?',
  'Describe your day using only emojis.',
  'If you could have any mythical or fictional creature as your pet, what would it be?',
  'In an alternate universe where your job is completely different, what would you be doing?',
  'What are your plans for the weekend?',
  'What interesting things have you done in the last month?',
  'What is your ultimate comfort food?',
  'If you could put one item into a time capsule, what would it be?',
  'If you could write a letter to yourself in ten years, what would it say?',
  'What is the most unique piece of furniture or decor you own?',
  'If you could redesign any room in your home, which one would it be and why?',
  'If you could make one positive, but unconventional, change in the world, what would it be?',
  'What is your all-time favourite TV show and why?',
  'Do you prefer to binge-watch shows or savour them one episode at a time?',
  'If you could bring back any canceled TV show for another season, which one would it be?',
  'What inspired you to pursue your current career or profession?',
  'What is the most interesting or unusual app you have on your phone?',
  'If you could create a hybrid animal by combining characteristics of two existing species, what would it be and why?',
  'If you wake up early on a weekend, do you stay up or try to go back to sleep?',
  'When you have a free afternoon, do you prefer to spend it indoors or outdoors?',
  'If you could pick any fictional world to live in, which one would you choose?',
  'When you get a new gadget, do you read the manual first or figure it out as you go?',
  'If you could instantly become an expert in one skill, what would it be?',
  "When you're trying a new restaurant, do you order something familiar or something adventurous?",
  'If you find a great new show, do you binge-watch it or space it out?',
  'When you exercise, do you prefer to do it alone or with a group?',
  'If you have a long flight, do you prefer to sleep or stay entertained?',
  'When decorating a space, do you plan everything out or improvise as you go?',
  'If you could switch lives with any celebrity for a day, who would it be?',
  'When you cook, do you follow a recipe strictly or improvise?',
  'If you have to wait in a long line, do you bring something to do or people-watch?',
  'When you listen to music, do you prefer playlists or entire albums?',
  'If you could relive any year of your life, which one would it be?',
  'When faced with a challenge, do you tackle it head-on or take time to think it through?',
  'If you could only eat one type of cuisine for a month, which would it be?',
  'When planning a vacation, do you prefer city exploration or relaxing on a beach?',
  'If you find a bug in your food at a restaurant, do you ask for a new dish or just stop eating?',
  'When you have a choice between two movies to watch, do you choose based on genre or reviews?',
  'When your favorite TV show is airing its final episode, do you watch it live or save it for later?',
  "If you're caught in the rain without an umbrella, do you find shelter or make a run for it?",
  'When you see a long line at your favorite coffee shop, do you wait or go somewhere else?',
  "If you're running late for a meeting, do you text ahead or just show up as soon as possible?",
  'When traveling, do you prefer to stick to a strict itinerary or go with the flow?',
  "If you're in the middle of a good book and it gets late, do you keep reading or go to sleep?",
  'When you discover a new hobby, do you dive deep into it immediately or take your time exploring?',
  'If you get lost in a new city, do you ask for directions or use a map app?',
  'When attending a concert, do you prefer seats close to the stage or further back for a better view?',
  'If you have a day off, do you prefer to plan activities or enjoy a lazy day?',
  'When shopping for clothes, do you prefer to shop alone or with friends?',
  'If you had to choose between a scenic road trip or a quick flight, which would you pick?',
  'When reading a book, do you prefer physical copies or e-books?',
  'If you could only listen to one genre of music for a year, which would it be?',
  'When watching a sports game, do you prefer to be in the stadium or watch from home?',
  'If you could instantly master one musical instrument, which would it be?',
  'When organizing your home, do you prefer a minimalist or cozy, cluttered style?',
  'If you have to give a presentation, do you prepare extensively or wing it?',
  'When faced with multiple tasks, do you tackle the hardest one first or the easiest?',
  'When meeting someone new, do you prefer small talk or deep conversations?',
  'When you find a series you love, do you share it with everyone or keep it to yourself?',
  'If you had a choice between unlimited books or unlimited movies, which would you pick?',
  'If you could have a home with a view of the ocean or the mountains, which would you choose?',
  'When it comes to learning, do you prefer hands-on experience or traditional study methods?',
];
