export const ICE_BREAKERS: string[] = [
  'What incredibly common thing have you never done?',
  'What was your most memorable dream?',
  'What household chore do you actually enjoy?',
  "What's the best thing you've got going on in your life at the moment?",
  "What was the funniest thing you've seen recently online?",
  'What are some of your favourite games to play?',
  'What topic could you give a 20-minute presentation on without any preparation?',
  "Who is the most interesting person you've met and talked with?",
  "What's your favourite car that you've owned or driven?",
  "What subjects should be taught in school but aren't?",
  'Do you think you have a pretty good work-life balance? Why or why not?',
  'What was the last thing you were really excited about?',
  'If you could choose your dreams, what would you prefer to dream about?',
  'What do you buy way more of than most people?',
  'What motivates you?',
  'What skill or talent would you most like to learn?',
  'What big problem do you think technology will solve next?',
  'What were your favourite television shows when you were growing up?',
  'What do you want to do when you retire?',
  'What was your funniest or worst experience with a dentist?',
  'What TV show are you hooked on or were recently hooked on?',
  'What brands do you love/hate the most?',
  'Who was your favourite teacher?',
  'How often do you dance?',
  "What's the best day you've had recently?",
  "What's the best advice you've been given?",
  "What's the worst advice you've been given?",
  'If the universe is just a simulation, what update or patch does it need?',
  "What's the best sports game you've been to?",
  "What's something you're looking forward to?",
  'What was a time you were totally out of your element/comfort zone?',
  'What kind of people do you most enjoy hanging out with?',
  'What do you think the ideal age to be is?',
  'What is the best thing you have ever bought?',
  "What's the best concert you've been to and why was it so good?",
  'If you could be somebody else for a day who would you be?',
  'Would you rather have more money or more time?',
  'If you could learn any language from another country which would you choose?',
  "What's the most important thing you have on or near your desk right now?",
  'What is your go-to drink or snack while working?',
  'Which website do you most often defer to when procrastinating?',
  'How often do you work from your bed?',
  'Name one colleague who is the most likely to escape a deserted island alive?',
  'If given the opportunity to be the boss for a day, which is the first thing you would do?',
  'What is your favourite thing about your team?',
  "What's the worst thing about working from home?",
  'If trapped in a horror movie, who would be the first one to die from your team?',
  "What's on your bucket list?",
  "What's something you've tried that you will never do again?",
  'In high school, what was the stupidest thing you did?',
  "What's the story behind your name?",
  'Would you rather live forever but have a boring life, or live a short but amazing life?',
  'What was the last thing you bought?',
  'What was the last song you listened to?',
  'What was your best class in school?',
  'What characteristic do you value the most in your coworkers?',
  'Cake or pie?',
  'If there was a movie about your life, which actor would play you?',
  'If you were a character in Shrek, which one would you be?',
  'What is your favourite theme park ride?',
  'What condiments go on your hotdog?',
  'What is your favourite ice cream flavour?',
  'What is your favourite cereal?',
  'Would you rather live your life as a dog or a cat?',
  'What is your favourite holiday?',
  'What is your favourite trend to come out of the past 10 years?',
  'What was the kindest thing a stranger ever did for you?',
  'What was your first job?',
  'Have you been pleasantly surprised by anything lately?',
  'Pick the person whose turn is next. What is something that they say/do often?',
  'If you could set up a chat between 2 famous people (dead or alive), who would you pick?',
  "What's your favourite scent?",
  'If you could see one movie again for the first time, what would it be and why?',
  'You have your own late-night talk show. Who do you invite as your first guest (dead or alive)?',
  'If you could go back in time 10,000 years ago and make a cave painting to confuse everyone in the future, what would you draw?',
  'Would you rather talk like Yoda or breathe like Darth Vader?',
  "If aliens landed on Earth, what do you think they'd find the most bizarre?",
  'Would you rather live 100 years in the past or 100 years in the future?',
  'What is your go-to outfit when you want to feel confident and stylish?',
  'If you were a flavour of ice cream, what would you be, and why?',
  'What is your signature dance move, and can you show us a quick demonstration?',
  'If you had a magic wand and could fix one everyday annoyance, what would it be?',
  'If you could have any fictional technology or gadget from a movie, what would it be, and how would you use it?',
  'If you were a professional wrestler, what would be your signature move?',
  'What is your favourite gadget or piece of technology that you cannot live without?',
  'If you were stranded on a deserted island and could only bring three items, what would they be?',
  'If you could redesign the human body, what would you change or improve?',
  'Are you a morning person or a night owl?',
  'Adventure or relaxation?',
  'Online shopping or in-store shopping?',
  "What is the most interesting fact you've learned recently?",
  'If you could witness any historical event, what would it be and why?',
  'If aliens visited Earth and you had to impress them with one skill, what would you do?',
  "What's your best 'dad joke' or pun?",
  'What is the most valuable lesson life has taught you so far?',
  'If you could add one unconventional room to your house, what would it be used for?',
  'If you were an online influencer, what kind of content would you create?',
  'If you could only follow one person on social media, who would it be and why?',
  'Should major life decisions be made with the head or the heart?',
  'Is it more polite to be nice or honest?',
  'What does your perfect breakfast look like?',
  'Describe your day using only emojis.',
  'If you could have any mythical or fictional creature as your pet, what would it be?',
  'In an alternate universe where your job is completely different, what would you be doing?',
  'If there was an office Olympics, what game would you excel at?',
  'What are your plans for the weekend?',
  'What interesting things have you done in the last month?',
  'What is your ultimate comfort food?',
  'If you could put one item into a time capsule, what would it be?',
  'If you could write a letter to yourself in ten years, what would it say?',
  'What is the most unique piece of furniture or decor you own?',
  'If you could redesign any room in your home, which one would it be and why?',
  'If you could make one positive, but unconventional, change in the world, what would it be?',
  'Do you have a favourite dish or recipe that your mom or dad makes?',
  'What is your favourite type of shoe (e.g. boots, sneakers, heels)?',
  'What is your all-time favourite TV show and why?',
  'Do you prefer to binge-watch shows or savour them one episode at a time?',
  'If you could bring back any canceled TV show for another season, which one would it be?',
];
